name: Compile

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        type: string
        required: false
        default: v1.0.0
  # push:
  #   branches: master

jobs:
  my_build:
    name: gcc compile
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: compile
      run: |
        echo Compiling...
        gcc ./hccapx2cap.c -o hccapx2cap
        echo Done.

    - name: delete tag and release
      uses: dev-drprasad/delete-tag-and-release@v1.0
      with:
        tag_name: ${{ inputs.tag }}
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ inputs.tag }}
        release_name: Release ${{ inputs.tag }}
        body: |
          Changes in this Release
          - None
        draft: false
        prerelease: false

    - name: upload binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./hccapx2cap
        asset_name: hccapx2cap
        asset_content_type: application/octet-stream