on:
  workflow_dispatch:

jobs:
  my_build:
    name: gcc compile
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: compile
      run: |
        echo Compiling...
        gcc ./hccapx2cap.c -o hccapx2cap
        echo Done.
